public with sharing class cc_pmt_FirstData_Params {
	public static final String PARAM_RESPONSE_CODE = 'x_response_code';
	public static final String PARAM_RESPONSE_SUBCODE = 'x_response_subcode';
	public static final String PARAM_RESPONSE_REASON_CODE	 = 'x_response_reason_code	';
	public static final String PARAM_RESPONSE_REASON_TEXT = 'x_response_reason_text';
	public static final String PARAM_AUTH_CODE = 'x_auth_code';
	public static final String PARAM_TRANS_ID = 'x_trans_id';
	public static final String PARAM_MD5_HASH = 'x_MD5_Hash';
	public static final String PARAM_AVS_CODE = 'x_avs_code';
	public static final String PARAM_CVV2_CODE = 'x_cvv2_resp_code';
	public static final String PARAM_CAVV_CODE = 'x_cavv_response';
	public static final String PARAM_EXACT_WSP_VERSION = 'exact_wsp_version';
	public static final String PARAM_EXACT_CTR = 'exact_ctr';
	public static final String PARAM_AUTH_NUM = 'Authorization_Num';
	public static final String PARAM_BANK_MESSAGE = 'Bank_Message';
	public static final String PARAM_BANK_RESP_CODE = 'Bank_Resp_code';
	public static final String PARAM_BANK_RESP_CODE_2 = 'Bank_Resp_code_2';
	public static final String PARAM_CARDHOLDER_NAME = 'CardHoldersName';
	public static final String PARAM_CLIENT_EMAIL = 'Client_Email';
	public static final String PARAM_CUSTOMER_NUM = 'Customer_Ref';
	public static final String PARAM_AMOUNT = 'DollarAmount';
	public static final String PARAM_EXACT_MESSAGE = 'Exact_Message';
	public static final String PARAM_EXACT_RESP_CODE = 'Exact_Resp_code';
	public static final String PARAM_LANGUAGE = 'Language';
	public static final String PARAM_REFERENCE_NO = 'Reference_No';
	public static final String PARAM_SEQUENCENO = 'SequenceNo';
	public static final String PARAM_TRANSACTION_CARD_TYPE = 'TransactionCardType';
	public static final String PARAM_TRANSACTION_APPROVED = 'Transaction_Approved';
	public static final String PARAM_TRANSACTION_ERROR = 'Transaction_Error';
	public static final String PARAM_TRANSACTION_TAG	 = 'Transaction_Tag	';
	public static final String PARAM_AVS = 'AVS';
	public static final String PARAM_CAVV = 'CAVV';
	public static final String PARAM_CAVV_Algorithm = 'CAVV_Algorithm';
	public static final String PARAM_CAVV_RESPONSE = 'CAVV_Response';
	public static final String PARAM_CVD_PRESENCE_IND = 'CVD_Presence_Ind';
	public static final String PARAM_CVV2 = 'CVV2';
	public static final String PARAM_CARD_NUMBER = 'Card_Number';
	public static final String PARAM_Ecommerce_Flag = 'Ecommerce_Flag';
	public static final String PARAM_RETRIEVAL_REF_NO = 'Retrieval_Ref_No';
	public static final String PARAM_XID = 'XID';
	public static final String PARAM_ZipCode = 'ZipCode';
		
	public cc_pmt_FirstData_Params() {
	}
}