@isTest
private class mapquest_Functions_Test {
/*
  public static testMethod void testthis() {
    account a = new Account(
     name = 'Test Account',
     SAP_Street__c = '242 DEMONT RD',
     SAP_City__c = 'CHESTER BASIN',
     SAP_State__c = 'Nova Scotia',
     SAP_Zip_Code__c = 'B0J 1K0',
     SAP_Country__c = 'CA',
     Address_Updated__c = true
    );

     insert a;
     system.debug('Test My Account: ' + a);
     a = [select id, shippingstreet, shippingcity, shippingstate, shippingpostalcode, shippingcountry, Mapquest_address__c from account where id = :a.id limit 1];
     system.debug('Test My Account: ' + a);
     
     Map<Id, mapquest_functions.LatLng> coords = mapquest_functions.getLatLngs(new List<Account>{a});
     system.debug('coords: ' + coords);
     mapquest_functions.calculateDistance(coords.get(a.id).lat, coords.get(a.id).lng,
                                          coords.get(a.id).lat, coords.get(a.id).lng); 
     
     Mapquest_batch b = new Mapquest_batch('and id = \'' + a.id + '\'');
     id idbatch = database.executebatch(b);           
   }
   */
}