@isTest
    public class mapquest_response_Test{/*      
        public static testMethod void Testmapquest_response(){
            mapquest_response.options  op = new mapquest_response.options(2,true,true);
            mapquest_response.copyright cr = new mapquest_response.copyright('test','test','test');
            mapquest_response.displayLatLng dll = new mapquest_response.displayLatLng(1,2);
            mapquest_response.latLng ll = new mapquest_response.latLng(1,2);
            mapquest_response.providedLocation pl = new mapquest_response.providedLocation('test');
            mapquest_response.location loc = new mapquest_response.location('1','2','3','4','5','6','7','8',true,'9','10','11','12',ll,dll);
            list<mapquest_response.location> mrl = new list<mapquest_response.location>();
            list<string> str = new list<string>();
            mapquest_response.result res = new mapquest_response.result(pl,mrl);
            mapquest_response.info inf = new mapquest_response.info(1,cr,str);
            list<mapquest_response.result> lrs = new list<mapquest_response.result>();
            mapquest_response mrp = new mapquest_response(inf,op,lrs);
        }*/
    }