public class mapquest_response{
/*
public info info{Get; set;}
public options options{Get; set;}
public List<Result> results{get; set;}
public Mapquest_response(info info, options options, List<Result> results){
  this.info = info;
  this.options = options;
  this.results = results;
}

public class info{
  public integer statuscode{get; set;}
  public copyright copyright{get; set;}
  public List<string> messages{get; set;}
  
  public info(integer statuscode, copyright copyright, List<String> messages){
    this.statuscode = statuscode;
    this.copyright = copyright;
    this.messages = messages;
  }
}

public class options{
  public integer maxResults{get; set;}
  public boolean thumbMaps{get; set;}
  public boolean ignoreLatLngInput{get; set;}
  
  public options(integer maxResults, boolean thumbMaps, boolean ignoreLatLngInput){
    this.maxResults = maxResults;
    this.thumbMaps = thumbMaps;
    this.ignoreLatLngInput = ignoreLatLngInput;
  }
}

public class result{
  public providedLocation providedLocation{get; set;}
  public List<Location> locations{Get; set;}
  
  public result(providedLocation providedLocation, List<Location> locations){
    this.providedLocation = providedLocation;
    this.locations = locations;
  }

}

public class Location{
  public string street{Get; set;}
  public string adminArea5{Get; set;}
  public string adminArea5Type{get; set;}
  public string adminArea4{Get; set;}
  public string adminArea4Type{get; set;}
  public string adminArea3{Get; set;}
  public string adminArea3Type{get; set;}
  public string adminArea2{Get; set;}
  public string adminArea2Type{get; set;}
  public string adminArea1{Get; set;}
  public string adminArea1Type{get; set;}
  public string postalCode{get; set;}
  public string geocodeQuality{Get; set;}
  public boolean dragPoint{Get; set;}
  public string sideOfStreet{Get; set;}
  public string linkId{Get; set;}
  public string unknownInput{Get; set;}
  public string type{get; set;}
  public latLng latLng{Get; set;}
  public displayLatLng displayLatLng{Get; set;}

  public Location(string street, string adminArea5, string adminArea4, string adminArea3, string adminArea2, string adminArea1, string postalCode, string geocodeQuality,
                  boolean dragPoint, string sideOfStreet, string linkId, string unknownInput, string type, latLng latLng, displayLatLng displayLatLng){
     
     this.street = street;
     this.adminArea5 = adminArea5;
     this.adminArea4 = adminArea4;
     this.adminArea3 = adminArea3;
     this.adminArea2 = adminArea2;
     this.adminArea1 = adminArea1;
     this.postalCode = postalCode;
     this.geocodeQuality = geocodeQuality;
     this.dragPoint = dragPoint;
     this.sideOfStreet = sideOfStreet;
     this.linkId = linkId;
     this.unknownInput = unknownInput;
     this.type = type;
     this.latLng = latLng;
     this.displayLatLng = displayLatLng;
     
          
 }


}

public class latLng{
  public double lat{Get; set;}
  public double lng{get; set;}
  public latLng(double lat, double lng){
    this.lat = lat;
    this.lng = lng;
  }
}

public class displayLatLng{
  public double lat{Get; set;}
  public double lng{get; set;}
  public displayLatLng(double lat, double lng){
    this.lat = lat;
    this.lng = lng;
  }
}

public class providedLocation{
  public string street{Get; set;}
  public providedLocation(string street){
    this.street = street;
  }
}

public class copyright{
     public string text{get; set;}
     public string imageURL{get; set;}
     public string imageAltText{Get; set;}
     
     public copyright(string text, string imageURL, string imageAltText){
        this.text = text;
        this.imageURL = imageURL;
        this.imageAltText = imageAltText;
     }
  }
  */
}