public class Requesterlookup1Tests{
    /*
    //commented by Rajeev 1st july 2014
    static testMethod void testowneridupdate() {
         
       Sample_Analysis_Request__c sar=new Sample_Analysis_Request__c();
      sar.Requested_by__c='005E0000001vmmO';
      sar.Buisness_Group__c='Corporate Accounts';
      sar.Customer__c='001E000000BugxO';
      sar.Sample_Name__c='test';
      sar.Number_of_Samples__c='1';
      sar.Analysis_Type__c='Customer Complaint - Product Used';
      sar.Comments__c='fdgfhgfhjfhg';
      insert sar;
      
      Certificate_Of_Analysis__c cofa1=new Certificate_Of_Analysis__c();
        cofa1.Batch__c='MC02BEE05';
        cofa1.Material__c='a0eE0000000Uhb8';
        cofa1.Supplier_Name__c='001E000000BtKEj';
        insert cofa1;
        
   }*/
   
}