/***********************************************************************************************************************   
Nexeo Solutions    
---------------------------------------------------------------------------------------------------------------------
*
*   Date Created:        08/15/2016
*    Author:                  Rohini Bharambe
*   Last Modified:        08/15/2016
*   Last Modified By:   Rohini Bharambe
*
*   Short Description:  This class is used to prevent recusive update of Account during Account Group creation.
*   **********************************************************************************************************************/

public class updation
{
    public static boolean isfutureupdate=false;
}